apiVersion: maupu.org/v1beta1
kind: VaultSecret
metadata:
  name: vault-secret
spec:
  secretName: secret
  secrets:
  - secretKey: foo
    path: secret1/secret
    kvPath: kubernetes
    field: foo
  - secretKey: another
    path: secret2/secret
    kvPath: kubernetes
    field: another
  syncPeriod: 1m
  config:
    addr: http://vault.vault:8200
    auth:
      kubernetes:
        role: admin
        cluster: kubernetes/local
