// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecret":       schema_pkg_apis_maupu_v1beta1_VaultSecret(ref),
		"github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecretSpec":   schema_pkg_apis_maupu_v1beta1_VaultSecretSpec(ref),
		"github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecretStatus": schema_pkg_apis_maupu_v1beta1_VaultSecretStatus(ref),
	}
}

func schema_pkg_apis_maupu_v1beta1_VaultSecret(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VaultSecret is the Schema for the vaultsecrets API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecretSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecretStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecretSpec", "github.com/nmaupu/vault-secret/pkg/apis/maupu/v1beta1.VaultSecretStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_maupu_v1beta1_VaultSecretSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VaultSecretSpec defines the desired state of VaultSecret",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_maupu_v1beta1_VaultSecretStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VaultSecretStatus defines the observed state of VaultSecret",
				Type:        []string{"object"},
			},
		},
	}
}
