# Adds namespace to all resources.
namespace: vault-secrets

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: vault-secret-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
- namespace.yaml

bases:
- ../../../config/crd
- ../../../config/rbac
- ../../../config/manager


# watch all namespaces
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vault-secret
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/0
